<?php
// module/Album/view/device/device/index.phtml:
$title = 'My Device';
$jquerySrc =   'http://code.jquery.com/jquery-1.9.1.js';
$jqueryUiSrc =   'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
$this->headTitle($title);
$this->headScript()->prependFile($jqueryUiSrc);
$this->headScript()->prependFile($jquerySrc);
$this->headScript()->appendFile( "/js/sortableTest.js", $type = 'text/javascript' );

$this->headLink()->appendStylesheet('/css/themes/base/jquery-ui.css');
$this->headLink()->appendStylesheet('/css/style.css');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('device', array('action'=>'add'));?>">Add new issue</a>
</p>

<table class="table">
<tr>
    <th>Issue ID</th>
    <th>Subject </th>
    <th>App </th>
    <th>Device </th>
    <th>PLM </th>
    <th>Redmine </th>
    <th>Type </th>
    <th>Status </th>
    <th>Assignee </th>
    <th>Created </th>
    <th>Pending </th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($issues as $issue) : ?>
<tr>
    <td><?php echo $this->escapeHtml($issue->id);?></td>
    <td><?php echo $this->escapeHtml($issue->subject);?></td>
    <td><?php echo $this->escapeHtml($issue->app);?></td>
    <td><?php echo $this->escapeHtml($issue->devices);?></td>
    <td><?php echo $this->escapeHtml($issue->plm);?></td>
    <td><?php echo $this->escapeHtml($issue->url);?></td>
    <td><?php echo $this->escapeHtml($issue->type);?></td>
    <td><?php echo $this->escapeHtml($issue->status);?></td>
    <td><?php echo $this->escapeHtml($issue->assignee_mail);?></td>
    <td><?php echo $this->escapeHtml($issue->created);?></td>
    <td><?php echo $this->escapeHtml($issue->count);?></td>
    <td>
    </td>
</tr>
<?php endforeach; ?>
</table>

<form name="upload-form" id="upload-form" method="post" enctype="multipart/fnorm-data">
    <div class="form-element">
        <label for="image-file">Avatar Image Upload</label>
        <input type="file" name="image-file" id="image-file">
    </div>

    <button>Submit</button>
</form>