<?php
$title = 'Redmine Data Mining';
$jquerySrc =   'http://code.jquery.com/jquery-1.9.1.js';
$jqueryUiSrc =   'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
$this->headTitle($title);
$this->headScript()->prependFile($jqueryUiSrc);
$this->headScript()->prependFile($jquerySrc);
$this->headScript()->appendFile( "http://html5shiv.googlecode.com/svn/trunk/html5.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js", $type = 'text/javascript' );
// $this->headScript()->appendFile( "/js/html5shiv.js", $type = 'text/javascript' );
// $this->headScript()->appendFile( "/js/respond.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/jquery.tablesorter.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/spin.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/highcharts/highcharts.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/highcharts/highcharts-3d.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/highcharts/modules/exporting.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/Redexcel_Form.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/jquery.ui.autocomplete.scroll.min.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/bootstrap.js", $type = 'text/javascript' );
$this->headLink()->appendStylesheet('/css/custom_eric.css');
$this->headLink()->appendStylesheet('/css/tablesorter_blue/style.css');
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<script type="text/javascript">
    var urlform           = '<?php echo '';//echo $this->url('album', array('controller'=>'album', 'action'=>'exlprep3forms')); ?>';
</script>
<p class="lead"> : displaying issue statistics for TAed devices</p>

<?php 
$form = $this->form;
?>
<hr>
<div class="form-horizontal form-block">
<?php $form->prepare(); // The correct enctype is set here ?>
        <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                        <label for="taskName" class="col-sm-2 ">Task Name</label>
                    <div class="col-sm-10">
                                <?php echo $this->formRow($form->get('taskName')); ?>
                        </div>
                </div>
                <div class="form-group form-table-group">
                        <label class="col-sm-2 ">Device Table <span class="required1"> *</span></label>
                    <div class="col-sm-10">
                                        <?php 
                                        $collections = $form->get('deviceVal');
                                        echo '<table class="table collectionTable"> 
                                                        <tr> <th>Device Name</th> <th>Other Names in Redmine</th> <th>Remove</th> </tr> ';
                                        foreach ($collections as $col) : ?>
                                                <tr>
                                                        <td> <?php echo $this->forminput($col->get('deviceName'));?> </td>
                                                        <td> <?php echo $this->forminput($col->get('deviceList'));?> </td>
                                                        <td> <?php //echo '<button type="button" class="btn btn-danger btn-sm" id="remove-button"><span class="glyphicon glyphicon-remove"></span></button>';?></td>
                                                </tr>
                                <?php  endforeach;
                                        echo '</table>';
                                        ?>
                                <!-- add button -->
                                <button class="addbtn">Add a device</button>
                        </div>
                </div>
                <hr> 
                <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                                <?php echo $this->formElement($form->get('submit')); ?>
                        </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
</div>

<!-- Result here -->

<hr>
<div class="col-sm-2"> </div>
<div id="chart_device_all"  style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>
<div class="col-sm-2"> </div>
<div id="chart_type_per_device" style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>
<div class="col-sm-2"> </div>
<div id="chart_type_per_app"  style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>
<div class="col-sm-2"> </div>
<div id="chart_issues_by_device"  style="height: 400px; margin: 0 auto"></div>

<hr>
<h4>Output</h4>
<div class="download col-sm-2 "> <h4> spreadsheet</h4></div>
<div class="download col-sm-10 "> <h4>
<!-- 
<a id="xlsdown" href="<?php 
		$urlParams = array('action' => 'download'); 
		$options = array(
	        'query' => array(
	            'filename' => 'RedExcel-TAed-Oct-30-14-am.xlsx',
	        ),
	    );
		echo $this->url('device', $urlParams, $options); 
		?>"> download here</a>
-->
<a id="xlsdown" href=""> download here</a>
</h4>
</div>
<h4 class="col-sm-2 ">ALL Issues</h4>
<div class="download col-sm-10" ><h4> Issue Table  </h4></div> 
<div class="download col-sm-12" id="issueTable"> </div> 

