<?php
// module/Album/view/album/album/index.phtml:
// File: upload-form.phtml
$title = 'My Uploader';
$jquerySrc =   'http://code.jquery.com/jquery-1.9.1.js';
$jqueryUiSrc =   'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
$this->headTitle($title);
$this->headScript()->prependFile($jqueryUiSrc);
$this->headScript()->prependFile($jquerySrc);
$this->headScript()->appendFile( "/js/sortableTest.js", $type = 'text/javascript' );

$this->headLink()->appendStylesheet('/css/style.css');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php echo 'hell world'; ?>
<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>

<div class="element element_name form-element">
    <?php echo $this->formRow($form->get('TmoTV')); ?>
</div>
<div class="element element_submit">
    <?php echo $this->formSumit($form->get('submit')); ?>
</div>

    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>

