<?php
// module/Album/view/album/album/index.phtml:
// File: upload-form.phtml
$title = 'Issue analyzer 2forms';
$jquerySrc =   'http://code.jquery.com/jquery-1.9.1.js';
$jqueryUiSrc =   'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
$this->headTitle($title);
$this->headScript()->prependFile($jqueryUiSrc);
$this->headScript()->prependFile($jquerySrc);
$this->headScript()->appendFile( "/js/jquery.tablesorter.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/bootstrap.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/spin.js", $type = 'text/javascript' );
$this->headScript()->appendFile( "/js/dynamicForm_mod.js", $type = 'text/javascript' );

// $this->headLink()->appendStylesheet('/bootstrap-3.0.1/css/bootstrap.css');
$this->headLink()->appendStylesheet('/css/custom_eric.css');
// $this->headLink()->appendStylesheet('/css/view.css');
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<script type="text/javascript">
    var urlform           = '<?php echo '';//echo $this->url('album', array('controller'=>'album', 'action'=>'exlprep3forms')); ?>';
</script>
<p class="lead"> :processing a spreadsheet to break down PLM issues app by app</p>

<!-- <div id="result"> test area</div> -->

<hr>
<!--  1st Form -->
<div class="form-horizontal form-block">
<?php $formsub->prepare(); // The correct enctype is set here ?>
        <?php echo $this->form()->openTag($formsub); ?>
        <div class="form-group">
                        <label class="col-sm-2 control-label">Have Template?</label>
                    <div class="col-sm-10">
                                <?php echo $this->formRow($formsub->get('uploadTmp')); ?>
                        </div>
                        
                        <div class ="row"> </div>
                        <label for="uploadExl" class="col-sm-2 control-label">Spreadsheet <span class="required1"> *</span> </label> 
                    <div class="col-sm-10">
                                <?php echo $this->formRow($form->get('uploadExl')); ?>
                        </div>
  
                        <div class ="row"> </div>
                        <div class="col-sm-2"> </div>
                        <div class="col-sm-10">
<!--                         <div class="col-sm-offset-2 col-sm-10"> -->
<!--                         <div class="col-xs-5"> -->
                                <?php echo $this->formElement($formsub->get('submit')); ?>
                        </div>
        </div>
<?php echo $this->form()->closeTag(); ?>
</div>

<hr>

<!--  2nd Form -->
<div class="form-horizontal form-block">
<?php $form->prepare(); // The correct enctype is set here ?>
        <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                        <label for="taskName" class="col-sm-2 control-label">Task Name</label>
                    <div class="col-sm-10">
                                <?php echo $this->formRow($form->get('taskName')); ?>
                        </div>
                </div>
<!--                 <div class="form-group"> -->
<!--                         <label class="col-sm-2 control-label">Have Template?</label> -->
<!--                     <div class="col-sm-10"> -->
                                <?php //echo $this->formRow($form->get('uploadTmp')); ?>
<!--                         </div> -->
<!--                 </div> -->
                <div class="form-group form-table-group">
                        <label class="col-sm-2 control-label">Search Table <span class="required1"> *</span></label>
                    <div class="col-sm-10">
                                        <?php 
                        //                         echo $this->formCollection($form->get('searchTerm'));
                                        $collections = $form->get('searchTerm');
                                        echo '<table class="table collectionTable"> 
                                                        <tr> <th>App Name</th> <th>Search terms</th> <th>Remove</th> </tr> ';
                                        foreach ($collections as $col) : ?>
                                                <tr>
                                                        <td> <?php echo $this->forminput($col->get('appName'));?> </td>
                                                        <td> <?php echo $this->forminput($col->get('regexPattern'));?> </td>
                                                        <td> <?php //echo '<button type="button" class="btn btn-danger btn-sm" id="remove-button"><span class="glyphicon glyphicon-remove"></span></button>';?></td>
                                                </tr>
                                <?php  endforeach;
                                        echo '</table>';
                                        ?>
                                <!-- add button -->
                                <button class="addbtn">Add a new category</button>
                        </div>
                </div>
                <hr>
                <div class="form-group">
                        <label class="col-sm-2 control-label">Search Fields <span class="required1"> *</span></label>
	                    <div class="col-sm-10" >
	                    <ul class="list-group" id="checkCells">
	                    </ul>
	                    </div>
                </div>
                <hr> 
<!--                 <div class="form-group"> -->
<!--                         <label for="uploadExl" class="col-sm-2 control-label">Spreadsheet <span class="required1"> *</span> </label>  -->
<!--                     <div class="col-sm-10"> -->
                                <?php //echo $this->formRow($form->get('uploadExl')); ?>
<!--                         </div> -->
<!--                 </div> -->
                <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                                <?php echo $this->formElement($form->get('submit')); ?>
                        </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
</div>

<!-- Result here -->


<div class="col-sm-2 "> <span class="glyphicon glyphicon-starr text-right"></span> </div>
<div class="col-sm-10" > <span class="glyphicon glyphicon-align-left text-right"></span></div>
<div class="download col-sm-2 text-right "> <h4> spreadsheet</h4></div>
<div class="download col-sm-10 "> <h4>
<a href="<?php 
$urlParams = array('action' => 'download');
echo $this->url('album', $urlParams); ?>"> download this</a>
</h4>
</div>

<div class="col-sm-10" id="result"> </div>
