<?php
// module/Album/view/album/album/index.phtml:
// File: upload-form.phtml
$title = 'My Uploader';
$jquerySrc =   'http://code.jquery.com/jquery-1.9.1.js';
$jqueryUiSrc =   'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
$this->headTitle($title);
$this->headScript()->prependFile($jqueryUiSrc);
$this->headScript()->prependFile($jquerySrc);
$this->headScript()->appendFile( "/js/sortableTest.js", $type = 'text/javascript' );

$this->headLink()->appendStylesheet('/bootstrap-3.0.1/css/bootstrap.css');
$this->headLink()->appendStylesheet('/css/custom_eric.css');
// $this->headLink()->appendStylesheet('/css/view.css');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<script>
    function add_category() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset').append(template);

        return false;
    }
</script>


<div class="jumbotron">
<div class="container-fluid">
    <div class="row-fluid" >
        <div class="centering text-center">
        <div class = "">
<?php $form->prepare(); // The correct enctype is set here ?>
	<?php echo $this->form()->openTag($form); ?>
		<div class="control-group1">
		 <div class="form-group1">
		<?php echo $this->formRow($form->get('TmoTV')); ?>
		</div>
		 <div class="form-group1">
		<?php echo $this->formCollection($form->get('searchTerm'));?>
		<button class="btn" onclick="return add_category()">Add a new category</button>
		</div>
		 <div class="form-group1">
		<?php echo $this->formRow($form->get('uploadTmp')); ?>
		</div>
		 <div class="form-group1">
		<?php echo $this->formRow($form->get('uploadExl')); ?>
		</div>
		 <div class="form-group1">
		<?php echo $this->formElement($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
	</div>
	</div>
	</div>
</div>

