<?php
// module/Album/view/album/album/index.phtml:
// File: upload-form.phtml
$title = 'PHPExcel read';
$jquerySrc =   'http://code.jquery.com/jquery-1.9.1.js';
$jqueryUiSrc =   'http://code.jquery.com/ui/1.10.3/jquery-ui.js';
$this->headTitle($title);
$this->headScript()->prependFile($jqueryUiSrc);
$this->headScript()->prependFile($jquerySrc);
$this->headScript()->appendFile( "/js/sortableTest.js", $type = 'text/javascript' );

$this->headLink()->appendStylesheet('/css/style.css');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo 'hell world'; ?>

